# Copyright 2020, the JFlex team
#
# SPDX-License-Identifier: BSD-2-Clause

name: Build

on:
  push:
    branches:
      - master
  pull_request:

env:
  PUBLISH_SOURCES: 'true'

# FIXME: make this a matrix build (macos/windows x different jdks)

jobs:
  build:
    name: 'Maven'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: 'ğŸ”¨ Maven (build, test)'
      run: scripts/test-unit.sh
    - name: 'ğŸ”¨ Maven (site)'
      run: scripts/mvn-site.sh
    - name: 'ğŸ”¨ Maven (aggregate sources)'
      run: scripts/mvn-aggregate-srcs.sh
# needs update for github:
#      run: scripts/preparare-deploy-source-code.sh

  regression:
    name: 'Regression Test'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: 'ğŸ“ Regression tests'
      run: |
        scripts/mvn-install-fastbuild.sh jflex-maven-plugin,testsuite/jflex-testsuite-maven-plugin
        scripts/test-regression.sh

  examples:
    name: 'Examples'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        # FIXME: make matrix
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: 'ğŸ˜ Examples (mvn, ant, make)'
      run: scripts/test-examples.sh

  docs:
    name: 'Docs'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Install LaTeX and pandoc'
      run: |
        sudo apt-get install \
             pandoc pandoc-citeproc texlive texlive-latex-extra lmodern
    - name: "ğŸ“„ Documentation"
      run: cd docs; make
